"""A Claude Code slash command is a reader direction, and a harness control is not (DRC-4764).

A reader who directs a session with `/pr-review-response 1287 …` or `/review` gave a direction,
and before this the observed record dropped it: the record parsed as the reader's message, but
`project_context._semantic_line` skips every line that opens with `<`, and the command arrives
wholly in `<command-message>`, `<command-name>` and `<command-args>` tags. A reading could then
call work the reader asked for a departure, and the page did not list it as a later direction.

The fixtures are hand-written in the shapes measured over the local Claude store on 2026-10-01,
counts only: a prompt command (a skill, or a built-in that expands into a prompt) leads with
`<command-message>` and is followed by an `isMeta` record holding the expanded prompt; a local
command the harness runs itself (`/clear`, `/login`, `/compact`) leads with `<command-name>`,
usually after an `isMeta` `<local-command-caveat>` record, and is followed by
`<local-command-stdout>`. Every text here is placeholder prose, and the one credential shape is
the documented `AKIAIOSFODNN7EXAMPLE`.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from typing import Any
from unittest import mock

from cargento_runtime import (
    aggregate,
    claude_data,
    correction,
    observer,
    project_context,
    reading,
    records,
)
from cargento_runtime.config import build_runtime_config
from cargento_runtime.state import build_runtime_state

from . import test_direction_adoption as adoption
from .support import make_server, serve_until_closed
from .test_claude_checks import SHORT, START, Transcript
from .test_direction_adoption import _row

FIRST = "Add retry with backoff to the webhook handler."
ARGS = "1287 address the placeholder review comments"
DIRECTED = f"/pr-review-response {ARGS}"
NOW = START.timestamp() + 3600

CAVEAT = (
    "<local-command-caveat>Caveat: The messages below were generated by the user while running "
    "local commands. DO NOT respond to these messages or otherwise consider them in your "
    "response unless the user explicitly asks you to.</local-command-caveat>"
)


def prompt_command(name: str, args: str = "") -> str:
    """A prompt command as Claude Code records it: `<command-message>` first."""
    return (
        f"<command-message>{name}</command-message>\n"
        f"<command-name>/{name}</command-name>\n"
        f"<command-args>{args}</command-args>"
    )


def local_command(name: str, args: str = "") -> str:
    """A local command as Claude Code records it: `<command-name>` first."""
    return (
        f"<command-name>/{name}</command-name>\n"
        f"            <command-message>{name}</command-message>\n"
        f"            <command-args>{args}</command-args>"
    )


class Session(Transcript):
    """`Transcript` with the three slash-command record shapes added."""

    def _text(self, text: str, **extra: Any) -> dict[str, Any]:
        row = self._entry("user", [], **extra)
        # A command record's content is a bare string: 3,458 of the 3,470 measured.
        row["message"]["content"] = text
        return row

    def skill(self, name: str, args: str = "") -> None:
        self._text(prompt_command(name, args))
        self._entry(
            "user",
            [{"type": "text", "text": f"Base directory for this skill: /skills/{name}\n\n# Steps"}],
            isMeta=True,
        )

    def control(self, name: str, args: str = "") -> None:
        self._text(CAVEAT, isMeta=True)
        self._text(local_command(name, args))
        self._text("<local-command-stdout></local-command-stdout>")


class Board:
    """A real Claude Code transcript under a store root the resolver globs."""

    def __init__(self, root: Path) -> None:
        cwd = root / "work" / "billing"
        cwd.mkdir(parents=True)
        self.path = root / "claude" / "projects" / "-work-billing" / f"{SHORT}-full.jsonl"
        self.config = build_runtime_config(
            environ={"HOME": str(root), "CARGENTO_HOME": str(root / "state")},
            platform_name="linux",
            os_name="posix",
            launcher_path=root / "server.py",
            store_root_overrides={"claude.projects": str(root / "claude" / "projects")},
        )
        self.state = build_runtime_state(self.config, started=NOW)
        self.session = Session(cwd)
        self.session.prompt(FIRST)
        self.session.bash("pytest", "5 passed")

    def titles(self) -> list[str]:
        self.session.save(self.path)
        events = project_context.instruction_events(self.config, str(self.path), "claude", SHORT)
        return [str(event["title"]) for event in events]

    def facts(self) -> list[dict[str, Any]]:
        self.session.save(self.path)
        with mock.patch.object(observer.CodexGoalModel, "__call__", return_value=None):
            context = project_context.collect(
                self.config, self.state, [_row()], "billing", now=NOW, focus=("claude", SHORT)
            )
        return list(context["semantic"]["facts"])


class _SlashSession(unittest.TestCase):
    def setUp(self) -> None:
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.board = Board(Path(temp.name))
        self.config, self.state = self.board.config, self.board.state
        self.session = self.board.session

    def titles(self) -> list[str]:
        return self.board.titles()

    def facts(self) -> list[dict[str, Any]]:
        return self.board.facts()


class ASlashCommandIsAReaderDirectionTest(_SlashSession):
    def test_a_skill_command_with_arguments_is_a_direction_rendered_as_typed(self) -> None:
        self.session.skill("pr-review-response", ARGS)
        self.assertEqual([FIRST, DIRECTED], self.titles())

    def test_a_bare_skill_command_is_a_direction(self) -> None:
        # A skill invoked with no arguments is exactly what the reader asked for, as
        # `records.harness_control` already rules for the goal and the instruction line.
        self.session.skill("review")
        self.assertEqual([FIRST, "/review"], self.titles())

    def test_a_harness_control_is_not_a_direction_with_or_without_arguments(self) -> None:
        self.session.control("clear")
        self.session.control("login")
        # `/compact` carries its summary instructions as arguments on 85 of 90 records.
        self.session.control("compact", "keep the placeholder parser notes")
        self.session.control("add-dir", "/work/other")
        self.assertEqual([FIRST], self.titles())

    def test_a_prompt_command_on_the_shared_control_list_is_not_a_direction(self) -> None:
        # `/insights` expands into a prompt, so it leads with `<command-message>`, and the
        # list `records.harness_control` keeps for the goal slot already calls it a control.
        self.session.skill("insights")
        self.assertEqual([FIRST], self.titles())

    def test_the_expanded_prompt_after_a_command_is_never_a_direction(self) -> None:
        self.session.skill("create-pr")
        self.assertNotIn("Base directory", " ".join(self.titles()))

    def test_arguments_take_the_ordinary_redaction_and_bound(self) -> None:
        # The record parser masks the key before this reader sees it; `safe_text` is what strips
        # the bidi override, which would otherwise reorder how the row renders.
        args = "use AKIAIOSFODNN7EXAMPLE then \u202eword " + "word " * 60
        self.session.skill("pr-review-response", args)
        (_, title) = self.titles()
        self.assertTrue(title.startswith("/pr-review-response use "), title)
        self.assertNotIn("AKIAIOSFODNN7", title)
        self.assertIn(records.SECRET_MARKER, title)
        self.assertNotIn("\u202e", title)
        self.assertLessEqual(len(title), project_context.MAX_SEMANTIC_LINE)

    def test_multi_line_arguments_render_as_one_line_and_never_as_markup(self) -> None:
        # 19 measured records carry arguments over several lines; the old reader published the
        # continuation line, closing tag and all.
        self.session.skill("linear-deep-dive", "DRC-1\nthen the placeholder board")
        (_, title) = self.titles()
        self.assertEqual("/linear-deep-dive DRC-1 then the placeholder board", title)

    def test_the_command_reaches_the_ledger_as_a_person_entry(self) -> None:
        self.session.skill("pr-review-response", ARGS)
        ledger = reading.build_ledger(self.facts(), "claude", SHORT)
        (entry,) = [row for row in ledger if row["summary"] == DIRECTED]
        self.assertEqual("user_message", entry["type"])
        self.assertEqual(reading.AUTHOR_PERSON, entry["author"])

    def test_add_it_to_my_intent_reads_the_command_not_its_markup(self) -> None:
        self.session.skill("pr-review-response", ARGS)
        (fact,) = [f for f in self.facts() if f.get("summary") == DIRECTED]
        read = project_context.direction_text(
            self.config, self.state, "claude", SHORT, str(fact["fact_id"])
        )
        self.assertEqual((DIRECTED, False), (read.text, read.cut))


class WorkAfterASlashCommandWasAskedForTest(_SlashSession):
    def setUp(self) -> None:
        super().setUp()
        self.session.skill("pr-review-response", ARGS)
        self.session.edit(self.session.cwd + "/handler.py")
        self.facts_now = self.facts()

    def test_the_direction_precedes_the_work_it_asked_for_in_the_ledger(self) -> None:
        # A Claude Code check or write is listed under a tool-output grant, as the route passes it.
        ledger = reading.build_ledger(self.facts_now, "claude", SHORT, tool_output={})
        order = [row["summary"] for row in ledger]
        asked = order.index(DIRECTED)
        work = [i for i, row in enumerate(ledger) if row["work"]]
        self.assertTrue(work, order)
        self.assertLess(asked, work[-1])
        self.assertLess(ledger[asked]["at"], ledger[work[-1]]["at"])

    def test_it_is_an_unsettled_later_direction_of_the_first_prompt(self) -> None:
        first_at = next(float(f["at"]) for f in self.facts_now if f.get("summary") == FIRST)
        row = {"harness": "claude", "sid": SHORT}
        self.assertEqual(1, correction.unsettled_directions(row, self.facts_now, floor=first_at))


class OneControlRuleForTheGoalAndTheInstructionLineTest(_SlashSession):
    """The goal slot and the instruction line read controls by the event builder's rule.

    Before this they asked `records.harness_control` of the rendered line, a name list that
    matches only a bare command, so `/compact keep notes` was published as the session's goal and
    as the work it was asked for.
    """

    def goal(self) -> str:
        self.session.save(self.board.path)
        result = observer.analyze(
            self.config, self.state, str(self.board.path), now=NOW, window_sec=7 * 86400
        )
        return str(result["goal"])

    def line(self) -> dict[str, Any] | None:
        self.session.save(self.board.path)
        return claude_data.session_instruction(self.config, self.state, str(self.board.path))

    def test_a_local_command_with_arguments_is_never_the_goal(self) -> None:
        self.session.control("compact", "keep notes")
        self.assertEqual(FIRST, self.goal())

    def test_a_local_command_with_arguments_is_never_the_instruction(self) -> None:
        self.session.control("compact", "keep notes")
        line = self.line()
        assert line is not None
        self.assertEqual(("earlier", FIRST), (line["label"], line["text"]))

    def test_a_prompt_command_with_arguments_is_the_goal_and_the_instruction(self) -> None:
        self.session.skill("review", "some args")
        self.assertEqual("/review some args", self.goal())
        line = self.line()
        assert line is not None
        self.assertEqual(("asked", "/review some args"), (line["label"], line["text"]))

    def test_a_prompt_command_on_the_control_list_is_neither(self) -> None:
        self.session.skill("insights", "for the week")
        self.assertEqual(FIRST, self.goal())
        line = self.line()
        assert line is not None
        self.assertEqual("earlier", line["label"])


# Over the record reader's 2,000 characters, so the cut lands inside `<command-args>` and its
# closing tag never arrives: 2 of the 1,477 measured prompt commands.
HUGE_ARGS = " ".join(f"word{n}" for n in range(400)) + " FINAL"
# About 300 characters: whole, but more than a summary or an outcome line holds.
WIDE_ARGS = " ".join(f"step{n:03d}" for n in range(37))


class ACommandIsNeverShownWholeWhenItWasCutTest(_SlashSession):
    """A command the record reader cut is told as cut, and one it did not cut is told whole."""

    def opened(self, args: str) -> tuple[dict[str, Any], dict[str, Any]]:
        """`POST /api/direction` over a real socket, as "Add it to my intent" opens it."""
        self.session.skill("pr-review-response", args)
        fact = next(f for f in self.facts() if str(f.get("summary") or "").startswith("/pr-"))

        def collect(*_: Any) -> list[dict[str, Any]]:
            return [_row()]

        spec = aggregate.HarnessSpec(
            key="claude", label="Claude", discover=lambda *_: True, collect=collect
        )
        application = aggregate.Application(
            self.config,
            self.state,
            (spec,),
            native_notifier=lambda _p: "",
            popup_notifier=lambda _t, _b: None,
            diagnostic_sink=lambda _m: None,
            clock=lambda: NOW,
        )
        httpd = make_server(application=application)
        thread = serve_until_closed(httpd)
        try:
            status, body = adoption.DirectionRouteTest._post(
                httpd.server_port,
                "/api/direction",
                {"harness": "claude", "sid": SHORT, "fact_id": str(fact["fact_id"])},
            )
        finally:
            httpd.shutdown()
            thread.join(timeout=5)
        self.assertEqual(200, status)
        self.assertIs(True, body["ok"], body)
        return fact, body

    def test_a_cut_command_keeps_the_arguments_that_arrived(self) -> None:
        self.assertGreater(len(prompt_command("pr-review-response", HUGE_ARGS)), 2000)
        fact, _ = self.opened(HUGE_ARGS)
        self.assertTrue(str(fact["summary"]).startswith("/pr-review-response word0 word1"), fact)
        self.assertLessEqual(len(str(fact["summary"])), project_context.MAX_SEMANTIC_LINE)

    def test_add_it_to_my_intent_says_a_cut_command_was_clipped(self) -> None:
        _, body = self.opened(HUGE_ARGS)
        self.assertEqual((True, False), (body["clipped"], body["fits"]))
        self.assertTrue(body["text"].startswith("/pr-review-response word0 word1"), body)
        self.assertNotIn("FINAL", body["text"])
        self.assertTrue(body["text"].endswith("\u2026"), body["text"][-20:])

    def test_a_whole_wide_command_reaches_add_and_the_ledger_whole(self) -> None:
        typed = f"/pr-review-response {WIDE_ARGS}"
        self.assertGreater(len(typed), 290)
        fact, body = self.opened(WIDE_ARGS)
        got = {key: body[key] for key in ("text", "clipped", "fits")}
        self.assertEqual({"text": typed, "clipped": False, "fits": False}, got)
        # The published summary stays one title long; a reading reads the command whole
        # (the 2026-10-01 ruling `test_reader_words` covers).
        self.assertEqual(typed[: project_context.MAX_SEMANTIC_LINE], fact["summary"])
        ledger = reading.build_ledger(self.facts(), "claude", SHORT)
        (entry,) = [row for row in ledger if row["id"] == fact["fact_id"]]
        self.assertEqual(typed[: project_context.MAX_SEMANTIC_LINE], entry["summary"])
        self.assertEqual(typed, entry.get("words"))


if __name__ == "__main__":
    unittest.main()
